apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    service: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 30030
      name: http
      protocol: TCP
      targetPort: 80
      nodePort: 30030
