apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    rs: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: mysql.host
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: mysql.user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: mysql.password
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
