apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    service: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: service listening port
      name: http
      protocol: TCP
      targetPort: pod port or named port
      nodePort: machine port
