apiVersion: v1
kind: Namespace
metadata:
  name: emqx
  labels:
    name: emqx

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-configmap
  namespace: emqx
  labels:
    configMap: emqx
data:
  emqx.discovery: k8s
  emqx.name: emqx
  emqx.k8s-apiserver: http://masterIP:端口
  emqx.k8s-namespace: emqx
  emqx.k8s-service-name: emqx
  emqx.k8s-address-type: ip
  emqx.k8s-app-name: emqx

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  namespace: emqx
  labels:
    deployment: emqx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        - name: emqx-tcp
          containerPort: 1883
        - name: emqx-ssl
          containerPort: 8883
        - name: emqx-ws
          containerPort: 8083
        - name: emqx-wss
          containerPort: 8084
        - name: emqx-api-mgmt
          containerPort: 8080
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.discovery
        - name: EMQX_NAME
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.name
        - name: EMQX_CLUSTER__K8S__APISERVER
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.k8s-apiserver
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.k8s-namespace
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.k8s-service-name
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.k8s-address-type
        - name: EMQX_CLUSTER__K8S__APP_NAME
          valueFrom:
            configMapKeyRef:
              name: emqx-configmap
              key: emqx.k8s-app-name
        tty: true
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
  labels:
    service: emqx
spec:
  ports:
  - name: emqx-dashboard
    port: 31882
    nodePort: 31882
    targetPort:  emqx-dashboard
    protocol: TCP
  - name: emqx-tcp
    port: 31883
    nodePort: 31883
    targetPort:  emqx-tcp
    protocol: TCP
  - name: emqx-ssl
    port: 31884
    nodePort: 31884
    targetPort:  emqx-ssl
    protocol: TCP
  - name: emqx-ws
    port: 31885
    nodePort: 31885
    targetPort:  emqx-ws
    protocol: TCP
  - name: emqx-wss
    port: 31886
    nodePort: 31886
    targetPort:  emqx-wss
    protocol: TCP
  - name: emqx-api-mgmt
    port: 31887
    nodePort: 31887
    targetPort:  emqx-api-mgmt
    protocol: TCP
  selector:
    app: emqx
  type: NodePort
